### PR TITLE
Convert project to use with npm

### PR DESCRIPTION
**Pull request by b361asd**
Hello.

I saw your project on reddit and was really impressed! However, I saw that you were having trouble converting your project to use `npm`.

This pull request adds the `package.json` file needed for `npm` and puts the source `.js` files into the `src` directory to make it easier to navigate your project. It also adds easier instructions to the `README.md` file.

### CODE REVIEW

**Comment by ethans333** [comment]
Hey thank you so much for taking the time to fix my issue. I don't think I'm properly packaging it right. I cloned my repo with your pull requests and then ran
```
npm i puppeteer --save
npm i got --save
npm i terminal-image --save
```
Then ran
```
pkg main.js
```
And still, when I run the executable the app just crashes, any thoughts on what I'm doing wrong?

**Comment by b361asd** [comment]
Hi. Try these steps:

1. Clone the repo.
2. In the repo, run
   ```
   npm install
   ```
3. To start the app, run
   ```
   npm start
   ```

**Comment by ethans333** [comment]
Awesome it works! Is there any way I can package it as an executable?

**Comment by b361asd** [comment]
Hmm, I've never published a package before so I'm not sure how to. However, it looks like people publish their packages to the [npm](https://www.npmjs.com/) package repository so you could look up how to do that.

**Comment by ethans333** [comment]
Thanks, I'll check it out and merge the pull request.

**Comment by ethans333** [comment]
So if I wanted to add a new npm module to my project would I just do
```
npm i terminal-kit --save
```

**Comment by b361asd** [comment]
Yes. You can leave out the `--save` flag. So, the command would be:
```
npm i terminal-kit
```

**Pull request merged**
